export const categories = {
  1: { name: "Women",    banner: "https://images.pexels.com/photos/1074535/pexels-photo-1074535.jpeg?auto=compress&cs=tinysrgb&w=1600",   subCategories: ["Dresses", "Skirts", "Tops", "Coats"] },
  2: { name: "Men",     banner: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",   subCategories: ["Jackets", "Jeans", "Shirts", "Shoes"] },
  3: { name: "Children",banner: "https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=1600", subCategories: ["Tops", "Bottoms", "Shoes", "Accessories"] },
};

export const products = [
  // ---- Women (catId: 1) ----
  {
    id: 1,
    catId: 1,
    img: "https://images.pexels.com/photos/1972115/pexels-photo-1972115.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1163194/pexels-photo-1163194.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Long Sleeve T-Shirt",
    desc: "A classic long sleeve t-shirt perfect for any occasion. Made from premium cotton for ultimate comfort.",
    isNew: true,
    oldPrice: 19,
    price: 12,
  },
  {
    id: 2,
    catId: 1,
    img: "https://images.pexels.com/photos/1759622/pexels-photo-1759622.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Women's Coat",
    desc: "A stylish and warm coat, ideal for colder seasons. Tailored fit with high-quality fabric.",
    isNew: true,
    oldPrice: 17,
    price: 13,
  },
  {
    id: 3,
    catId: 1,
    img: "https://images.pexels.com/photos/1457983/pexels-photo-1457983.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Skirt",
    desc: "An elegant skirt with a flattering silhouette. Suitable for both casual and formal wear.",
    oldPrice: 20,
    price: 18,
  },
  {
    id: 4,
    catId: 1,
    img: "https://images.pexels.com/photos/2065200/pexels-photo-2065200.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Women's Hat",
    desc: "A fashionable hat to complete any outfit. Lightweight and comfortable for all-day wear.",
    oldPrice: 23,
    price: 19,
  },

  // ---- Men (catId: 2) ----
  {
    id: 5,
    catId: 2,
    img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/834863/pexels-photo-834863.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Men's Jacket",
    desc: "A rugged yet stylish men's jacket. Perfect for outdoor activities and casual outings.",
    isNew: true,
    oldPrice: 45,
    price: 35,
  },
  {
    id: 6,
    catId: 2,
    img: "https://images.pexels.com/photos/1684148/pexels-photo-1684148.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/52518/jeans-pants-blue-shop-52518.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Men's Jeans",
    desc: "Classic slim-fit men's jeans. Durable denim with a comfortable stretch for everyday wear.",
    oldPrice: 40,
    price: 29,
  },
  {
    id: 7,
    catId: 2,
    img: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Men's Polo Shirt",
    desc: "A breathable polo shirt for the modern man. Great for both smart-casual and formal settings.",
    isNew: true,
    oldPrice: 25,
    price: 18,
  },
  {
    id: 8,
    catId: 2,
    img: "https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1080558/pexels-photo-1080558.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Men's Sneakers",
    desc: "Lightweight and stylish sneakers for everyday comfort. Available in multiple colors.",
    oldPrice: 60,
    price: 45,
  },

  // ---- Children (catId: 3) ----
  {
    id: 9,
    catId: 3,
    img: "https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1620760/pexels-photo-1620760.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Kids Hoodie",
    desc: "A cozy and colourful hoodie for kids. Soft fleece lining keeps children warm and comfortable.",
    isNew: true,
    oldPrice: 20,
    price: 14,
  },
  {
    id: 10,
    catId: 3,
    img: "https://images.pexels.com/photos/1620760/pexels-photo-1620760.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=1600",
    title: "Kids Dress",
    desc: "An adorable dress for little ones. Machine washable fabric with vibrant prints.",
    oldPrice: 18,
    price: 12,
  },
  {
    id: 11,
    catId: 3,
    img: "https://images.pexels.com/photos/2421374/pexels-photo-2421374.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1105482/pexels-photo-1105482.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Kids Sneakers",
    desc: "Durable and lightweight sneakers designed for active kids. Non-slip sole for safety.",
    isNew: true,
    oldPrice: 30,
    price: 22,
  },
  {
    id: 12,
    catId: 3,
    img: "https://images.pexels.com/photos/1105482/pexels-photo-1105482.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/2421374/pexels-photo-2421374.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Kids Cap",
    desc: "A fun and protective cap for children. Adjustable strap fits all head sizes.",
    oldPrice: 12,
    price: 8,
  },
];
